version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
    time: '20:00'
  open-pull-requests-limit: 10

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
    time: '20:00'
  open-pull-requests-limit: 10
