language: go
go:
  - '1.7'
install:
  - make deps
script:
  - make ci-test
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - make cross-build
  - make dist
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: 'dist/*.{tar.gz,zip}'
  on:
    tags: true
    go: '1.7'
