language: go
go:
  - '1.7'
before_install:
  - mkdir -p $GOPATH/bin
install:
  - make deps
script:
  - make test
before_deploy:
  - make cross-build
  - make dist
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: 'dist/*.{tar.gz,zip}'
  on:
    tags: true
    go: '1.7'
