name: CI
on:
  push:
    branches:
      - master
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
      - run: GO111MODULE=on make test
