name: go mod tidy for Dependabot

on:
  pull_request:
    paths:
      - "go.mod"
      - "go.sum"

jobs:
  go-mod-tidy:
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          # Personal Access Token is required to trigger the consective CI jobs
          # https://github.com/stefanzweifel/git-auto-commit-action/tree/8040ba33d64985395ed5059f60a4d602cbefee73#commit-of-this-action-does-not-trigger-a-new-workflow-run
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
      - name: go mod tidy
        run: |
          go mod tidy
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          branch: ${{ github.head_ref }}
          commit_message: "go mod tidy"
          commit_author: Daisuke Fujita <dtanshi45@gmail.com>
