name: Release
on:
  push:
    tags:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
      - name: Build binaries
        run: GO111MODULE=on make cross-build
      - name: Build artifacts
        uses: dist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "dist/*.{tar.gz,zip}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
