name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Run tests
        run: GO111MODULE=on make ci-test
      - name: Send test coverage to Codecov
        uses: codecov/codecov-action@v1
